const geoLocation = [
    "Abdukarim",
    "Ahmad Yassaviy",
    "Alaja",
    "Alamli",
    "Altinko'l (Qo'ng'irot tumani)",
    "Andijon",
    "Angor",
    "Angren",
    "Arsif",
    "Asaka",
    "Avval",
    "Babalakota",
    "Baliqchi",
    "Balta",
    "Bardanko'l",
    "Baynalmilal",
    "Bekat",
    "Bekobod",
    "Bekobod (Bog'dod tumani)",
    "Beruni",
    "Beruniy (Qiyichirchiq tumani)",
    "Beshariq",
    "Beshkapa",
    "Beshkent",
    "Beshrabod",
    "Bo'jay",
    "Bo'ka",
    "Bo'rbaliq",
    "Bo'ston",
    "Bo'ston (Oltinsoy tumani)",
    "Bo'ston (Ellikqali tumani)",
    "Bo'ston (Zarbdor tumani)",
    "Bog'iturkon",
    "Bog'ot",
    "Bogdan",
    "Boyovut",
    "Boysun",
    "Buloqboshi",
    "Bulung'ur",
    "Burchmullo",
    "Buvayda",
    "Buxoro",
    "Bоg'dod",
    "Changi",
    "Chelak",
    "Chimboy",
    "Chimyon",
    "Chinabod",
    "Chinoz",
    "Chirchiq",
    "Chiroqchi",
    "Cho'rindi",
    "Chorbog'",
    "Chorraha",
    "Chortoq",
    "Chortoq (Guliston tumani)",
    "Chorvoq",
    "Chulkuvar",
    "Chust",
    "Chuvalachi",
    "Dang'ara",
    "Dangir",
    "Dasht",
    "Dashtobod",
    "Dehoji",
    "Dehqonobod",
    "Denov",
    "Denov (Shafirqon tumani)",
    "Do'rmon",
    "Do'stlik",
    "Do'stlik (Denov tumani)",
    "Do'stobod",
    "Dusimbiy",
    "Egizbuloq",
    "Eshmatoul",
    "Eshonguzor",
    "Fargʻona",
    "Farxod",
    "Fayziobod",
    "Forish",
    "Furqat",
    "G'alaba",
    "G'allaorol",
    "G'azalkent",
    "G'o's",
    "G'oliblar",
    "G'uzor",
    "Gagarin",
    "Galaosiya",
    "Galaquduq",
    "Gijduvon",
    "Gul",
    "Gulbahor",
    "Guliston",
    "Guliston (Yuqorichirchiq tumani)",
    "Gullanbog'",
    "Gulobod",
    "Gulzar",
    "Gulzar (Paxtakor tumani)",
    "Gurlan",
    "Hamzaobod",
    "Hayit",
    "Hisorak",
    "Humson",
    "Ibrat",
    "Iftixor",
    "Ishtixon",
    "Ispanza",
    "Istiqlol",
    "Ittifoq",
    "Jalaquduq",
    "Jambul",
    "Jarqo'rg'on",
    "Jayraxona",
    "Jilva",
    "Jizzax",
    "Jizzaxlik",
    "Jo'ynav",
    "Jomboy",
    "Jondor",
    "Juma",
    "Jumabazar (Bekobod tumani)",
    "Jumabazar (Yuqori Chirchiq tumani)",
    "Jumashuy",
    "Jurek",
    "Juren",
    "Kakaydi",
    "Kalkonota (Navbaxor tumani)",
    "Kangli",
    "Kanimex",
    "Kaptarxona",
    "Karamaz",
    "Karkidan",
    "Karmana",
    "Katta Ramadon",
    "Kattaqo'rg'on",
    "Kegayli",
    "Kelauchi",
    "Keles",
    "Kitob",
    "Ko'hna Kalon",
    "Ko'hna Sho'rcha",
    "Ko'kdala",
    "Ko'ksaroy",
    "Kogon",
    "Kosari",
    "Koson",
    "Kosonsoy",
    "Krasnogorsk",
    "Kulonxona",
    "Kumarik",
    "Kuyganyor",
    "Kuyun",
    "Labiro'd",
    "Lagan",
    "Lagandi",
    "Lalmiqor",
    "Lolazor",
    "Loyish",
    "Madaniyat",
    "Malikrabot",
    "Mang'it",
    "Margʻilon",
    "Marhamat",
    "Marjonbuloq",
    "Markaz",
    "Mashak",
    "Mindon",
    "Misr",
    "Muborak",
    "Mug'lon",
    "Mulkanlik",
    "Mulloyon",
    "Muratali",
    "Mustaqillik",
    "Namangan",
    "Namdanak",
    "Namuna",
    "Nanay",
    "Narpay (Karmana tumani)",
    "Navbahor",
    "Navbahor (Namangan tumai)",
    "Navoiiy",
    "Navoiy",
    "Navro'z",
    "Nazarbek",
    "Niyozbash",
    "Novaboshi",
    "Novkent",
    "Novmetan",
    "Nukus",
    "Nurafshon",
    "Nurobod",
    "Nurobod (Ohangaron tumani)",
    "Nurota",
    "O'rta Oqchi",
    "O'zbekiston",
    "Ohangaron",
    "Olimkent",
    "Olmaliq",
    "Olmazor (Chinoz tumani)",
    "Olot",
    "Oltiariq",
    "Oltinariq",
    "Oltinko'l",
    "Oqmang'it",
    "Oqoltin",
    "Oqqo'rg'on",
    "Oqtosh",
    "Ozod Vatan (Muzrobod tumani)",
    "Parchanxas",
    "Pargos",
    "Parkent",
    "Paxta (Chinoz tumani)",
    "Paxtachi",
    "Paxtakor",
    "Paxtaobod",
    "Paxtaobod (Sardoba tumani)",
    "Paxtazor",
    "Payariq",
    "Payshanba",
    "Pishagar",
    "Piskent",
    "Pitnak",
    "Pop",
    "Povulgon",
    "Poytug'",
    "Pushmon",
    "Qahramon",
    "Qamashi",
    "Qanliko'l",
    "Qaqir",
    "Qaravul",
    "Qarshi",
    "Qashqari",
    "Qatartol",
    "Qibray",
    "Qiziltepa",
    "Qo'g'ali",
    "Qo'ng'irot",
    "Qo'qon",
    "Qo'qonboy",
    "Qo'rg'oncha",
    "Qo'rg'ontepa",
    "Qo'shkupir",
    "Qo'shqo'rg'on",
    "Qo'shrobod",
    "Qo'shtepa",
    "Qora Xitoy",
    "Qoraboy",
    "Qorako'l",
    "Qoranko'l",
    "Qorao'zak",
    "Qoraqo'yli",
    "Qoraqushchi",
    "Qoraqushxona",
    "Qorashina",
    "Qorasuv",
    "Qorasuv (Qo'rg'ontepa tumani)",
    "Qorayantoq",
    "Qorovulbozor",
    "Qosh Yog'och",
    "Quduqcha",
    "Qumariqobod",
    "Qumqo'rg'on",
    "Qurama (Oltinsoy tumani)",
    "Qurbonov",
    "Quva",
    "Quvasoy",
    "Quyaboshi",
    "Rapqon",
    "Rishton",
    "Romitan",
    "Rovot",
    "Sabzikor",
    "Salar",
    "Samarqand",
    "Samarqandquduq",
    "Sanam",
    "Sang",
    "Sarbozor",
    "Sardoba",
    "Sariasiya",
    "Sarik (Qiziriq tumani)",
    "Saritepa",
    "Sasbaka",
    "Sayxun",
    "Shahrisabz",
    "Shahrixon",
    "Shamaton",
    "Shampan",
    "Sherobod",
    "Shirin",
    "Sho'ralisoy",
    "Sho'rchi",
    "Shodlik",
    "Shodlik (Oqoltin tumani)",
    "Shofirkon",
    "Shoyimbek",
    "Shumanay",
    "Shоvоt",
    "Sijjak",
    "Sirdaryo",
    "So'fon",
    "So'lti",
    "Sohibkor",
    "Sohil",
    "Soyliq",
    "Sukok",
    "Sulton Segizboyev",
    "Sutkibuloq",
    "Talkok",
    "Taxiatosh",
    "Taxtako'pir",
    "Teraktagi",
    "Termez",
    "Timiryazev",
    "Tinchlik",
    "To'qboy",
    "To'raqo'rg'on",
    "To'rtko'l",
    "Toshbuloq",
    "Toshkent",
    "Toshloq",
    "Toshloq (Qiyichirchiq tumani)",
    "Toyloq",
    "Turkmen",
    "Tuyabo'g'iz",
    "Uchko'prik",
    "Uchqizil",
    "Uchqo'rg'on",
    "Uchquduq",
    "Uchtepa",
    "Ulug'bek",
    "Umar",
    "Unqo'rg'on",
    "Unxayat",
    "Uramas",
    "Urganch",
    "Urgut",
    "Usmat",
    "Usmon Nosir",
    "Uychi",
    "Uyrat",
    "Uzun",
    "Vobkent",
    "Vodil",
    "Xalkobod",
    "Xalkobod (Yangiyo'l tumani)",
    "Xalkobod (Kegayli tumani)",
    "Xanka",
    "Xaqqulobod",
    "Xazarasp",
    "Xitoyan",
    "Xiva",
    "Xo'ja Yaqshba",
    "Xo'jaobod",
    "Xo'jarabot",
    "Xo'jasoat",
    "Xo'jayli",
    "Xo'jikent (Bo'stonliq tumani)",
    "Xonbandi",
    "Xonobod",
    "Xonziq",
    "Xorkash",
    "Xos",
    "Xovos",
    "Xusnobod",
    "Yakkabog'",
    "Yallama",
    "Yangi Chinoz (Chinoz tumani)",
    "Yangi Marg'ilon",
    "Yangi Mirishkar",
    "Yangi Nishon",
    "YangiHayot (Qiyichirchiq tumani)",
    "Yangiarik",
    "Yangibozor",
    "Yangibozor (Peshku tumani)",
    "Yangibоzоr (Yangibоzоr tumani)",
    "Yangiobod",
    "Yangiobod (Bo'ka tumani)",
    "Yangiovul",
    "Yangiqo'rg'on",
    "Yangirabat",
    "Yangiyer",
    "Yangiyo'l",
    "Yarkin",
    "Yaypan",
    "Yom",
    "Yozyovon",
    "Yuqori Bachqir",
    "Yuqori Valik",
    "Zafar",
    "Zafarobod",
    "Zafarobod (Konimex tumani)",
    "Zangiota",
    "Zarafshon",
    "Zarbdor",
    "Zarkent",
    "Zavrok",
    "Ziyodin",
    "Zomin",
    "Аyvalik"
]

const mahsulotKategoriya = [

    "Elektronika",
    "Maishiy texnika",
    "Kiyimlar",
    "Oyoq kiyimlari",
    "Aksessuarlar",
    "Go'zallik va g'amxo'rlik",
    "Salomatlik",
    "Uy-ro'zg'or buyumlari",
];

const catalogKategoriya = [
    {
        id: 2,
        img: "/icons/uzum.uz-elektronika.svg",
        title: "Elektronika",
        content: [
            {
                title: "Smartfonlar va telefonlar"
            }
        ]
    },
    {
        id: 3,
        img: "/icons/uzumuzum.uz-maishey-texnika.svg",
        title: "Maishiy texnika",
        content: ""
    },
    {
        id: 4,
        img: "/icons/maishiy_texnika.svg",
        title: "Kiyim",
        content: ""
    },
    {
        id: 5,
        img: "/icons/elektronika.svg",
        title: "Poyabzallar",
        content: ""
    }
    , {
        id: 6,
        img: "/icons/uzum.uz-elektronika.svg.svg",
        title: "Aksessuarlar",
        content: ""
    },
    {
        id: 7,
        img: "/icons/guzallik.svg",
        title: "Go'zallik va parvarish",
        content: ""
    },
    {
        id: 8,
        img: "/icons/salomatlik.svg",
        title: "Salomatlik",
        content: [
            {},
        ]
    },
    {
        id: 9,
        img: "/icons/uy-qurilish.svg",
        title: "uy-ro'zg'or buyumlari",
        content: ""
    },
    {
        id: 10,
        img: "/icons/qurilish-va-tamirlash.svg",
        title: "Qurilish va ta'mirlash",
        content: ""
    },
    {
        id: 11,
        img: "/icons/autotavar.svg",
        title: "Avtotovarlar",
        content: ""
    },
    {
        id: 12,
        img: "/icons/bolalartovarlari.svg",
        title: "Bolalar tovarlari",
        content: []
    },
    {
        id: 13,
        img: "/icons/hobbi.svg",
        title: "Xobbi va ijod",
        content: []
    },
    {
        id: 21,
        img: "/icons/sport.svg",
        title: "Sport va hordiq",
        content: []
    },
    {
        id: 14,
        img: "/icons/oziq-ovqat.svg",
        title: "Oziq-ovqat mahsulotlari",
        content: []
    },
    {
        id: 15,
        img: "/icons/kimyoviy.svg",
        title: "Maishiy kimyoviy moddalar",
        content: []
    },
    {
        id: 16,
        img: "/icons/kanselyara.svg",
        title: "Kanselyariya tovarlari",
        content: []
    },
    {
        id: 17,
        img: "/icons/hayvonlar.svg",
        title: "Hayvonlar uchun tovarlar",
        content: []
    },
    {
        id: 18,
        img: "/icons/kitoblar.svg",
        title: "Kitoblar",
        content: []
    },
    {
        id: 19,
        img: "/icons/bog.svg",
        title: "Dacha, Bog' va tomarqa",
        content: []
    },
    {
        id: 20,
        img: "/icons/salomatlik.svg",
        title: "Reabilitatsiya uchun subsidiyalangan mahsulotlar"
    }
]

const sliderImages = [
    "https://images.uzum.uz/d0dkfd0n274j5sclnom0/main_page_banner.jpg",
    "https://images.uzum.uz/d049tutpb7f46s8834ug/main_page_banner.jpg",
    "https://images.uzum.uz/cvcg2f3vgbkm5ehkika0/main_page_banner.jpg",
    "https://images.uzum.uz/d0ddtc0n274j5scll7v0/main_page_banner.jpg",
    "https://images.uzum.uz/d07o9rdpb7f46s88qkdg/main_page_banner.jpg",
    "https://images.uzum.uz/d03ipami4n37npapm39g/main_page_banner.jpg",
    "https://images.uzum.uz/d0cp5bojsv1iusmhnu90/main_page_banner.jpg",
    "https://images.uzum.uz/d0cs05dpb7f9p3nfg2bg/main_page_banner.jpg",
    "https://images.uzum.uz/cv4o265pb7f9qcng1frg/main_page_banner.jpg",
    "https://images.uzum.uz/d03ipsdpb7f46s87tj2g/main_page_banner.jpg",
    "https://images.uzum.uz/cvqaspmi4n37npankdg0/main_page_banner.jpg",
    "https://images.uzum.uz/cvc2fjbvgbkm5ehkfu70/main_page_banner.jpg",
    "https://images.uzum.uz/d0cp33gjsv1iusmhntt0/main_page_banner.jpg",
    "https://images.uzum.uz/d03iqdk7fd1idpht5ne0/main_page_banner.jpg",
    "https://images.uzum.uz/d08dgjtpb7f46s88vir0/main_page_banner.jpg",
    "https://images.uzum.uz/d07nnrmf4hvqhbr3vr2g/main_page_banner.jpg",
    "https://images.uzum.uz/d0cr9b0jsv1iusmhoj5g/main_page_banner.jpg",
    "https://images.uzum.uz/d0ctaii7s4fo7mq81ckg/main_page_banner.jpg",
    "https://images.uzum.uz/d0e5a6on274j5sclr0g0/main_page_banner.jpg",
    "https://images.uzum.uz/d07mq6lpb7f46s88q100/main_page_banner.jpg",
    "https://images.uzum.uz/cvqbgqs7fd1p445rop40/main_page_banner.jpg",
    "https://images.uzum.uz/d0cpqcdpb7f9p3nffbdg/main_page_banner.jpg",
    "https://images.uzum.uz/d0d610r3uvph509t1g40/main_page_banner.jpg",
    "https://images.uzum.uz/d0dir633uvph509t3nn0/main_page_banner.jpg",
];

const fourtProduct = [
    {
        id: 1,
        url: "https://static.uzum.uz/static/promo_images/756b6f56-9d2d-414c-a9d3-37d40d1c808b",
        title: "Onalar va bolalar uchun",
    },
    {
        id: 2,
        url: "https://static.uzum.uz/static/promo_images/65832182-a412-4676-994d-4d0ff4083253",
        title: "Arzon narxlar kafolati",
    },
    {
        id: 3,
        url: "https://static.uzum.uz/static/promo_images/bd2c8d3a-7488-4b12-84f8-0a816bc4a359",
        title: "Zamonaviy bozor",
    },
    {
        id: 4,
        url: "https://static.uzum.uz/static/promo_images/a98e3eef-162f-47b1-b8d8-f6253393bd95",
        title: "Hafta tovarlari",
    },
];


const data = {
    geoLocation,
    mahsulotKategoriya,
    sliderImages,
    fourtProduct,
    catalogKategoriya
};

export default data;
